version: '3'
services:
  DisasterInformationCollectionServer:
    build:
      context: ./DisasterInformationCollectionServer
    image: freemoon99/disaster-information-collection-server:latest
    ports:
      - "8081:8080"
  NotificationServer:
    build:
      context: ./NotificationServer
    image: freemoon99/disaster-notification-server:latest
    ports:
      - "8082:8080"
  ShelterInfoServer:
    build:
      context: ./ShelterInfoServer
    image: freemoon99/disaster-shelter-info-server:latest
    ports:
      - "8083:8080"
  UserServer:
    build:
      context: ./UserServer
    image: freemoon99/disaster-user-server:latest
    ports:
      - "8084:8080"
