version: '3'
services:
  DisasterInformationCollectionServer:
    image: freemoon99/disaster-information-collection-server:latest
    ports:
      - "8081:8081"
    depends_on:
      - redis
  NotificationServer:
    image: freemoon99/disaster-notification-server:latest
    ports:
      - "8082:8082"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
