spring:
    datasource:
        url: jdbc:mysql://shelterinfo.cztejv4vrupz.ap-northeast-2.rds.amazonaws.com/hanium
        username: root
        password: columbus0810
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop  # 서버가 켜져있는 동안만 유지
        properties:
            hibernate:
                format_sql: true  # SQL pretty print
                show-sql: true
    webmvc:
        cors:
            allowed-origins: http://localhost:3000
            allowed-methods: GET,POST,UPDATE
            allowed-headers: "*"
            allow-credentials: true

logging:
    level:
        root: debug

jwt:
    secret: 951ff84d4cc900bc82318cdc73025f5766a44d98e1fb0c9ed669628ad84440989b25194b577333b76c669ef13656461ec54731482a4141a63240d3aa21a57da7