name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build with Gradle
        run: |
          for server in "DisasterInformationCollectionServer" "NotificationServer" "UserServer"; do
            cd "$server"
            chmod +x ./gradlew
            ./gradlew build
            cd ..
          done
