name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Build and test
      run: |
        cd DisasterInformationCollectionServer
        chmod +x gradlew
        ./gradlew clean build

        cd ../NotificationServer
        chmod +x gradlew
        ./gradlew clean build

        cd ../ShelterInfoServer
        chmod +x gradlew
        ./gradlew clean build

        cd ../UserServer
        chmod +x gradlew
        ./gradlew clean build
        

    - name: Archive production artifacts 
      uses: actions/upload-artifact@v2 
      with:
        name: compiled-application 
        path : |
          DisasterInformationCollectionServer/build/libs/*.jar 
          NotificationServer/build/libs/*.jar 
          ShelterInfoServer/build/libs/*.jar 
          UserServer/build/libs/*.jar 

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name : Download built application jar files from artifacts.
      uses : actions/download-artifact@v2 
      with :
        name : compiled-application 

    - run : |
        mv DisasterInformationCollectionServer*.jar DisasterInformationCollectionServer/disaster-info-collection-server.jar   
        mv Notification*.jar Notification/disaster-notification-server.jar   
        mv ShelterInfo*.jar ShelterInfo/disaster-shelterinfo-server.jar   
        mv User*.jar User/disaster-user-server.jar   

    - name: Set up Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
